server:
  port: 8080

# Database configuration
spring:
  batch:
    initialize-schema: always
  datasource:
    driver-class-name: # driver
    jdbcUrl: # url
    username: # username
    password: # password
  jpa:
    hibernate:
      ddl-auto: update

application:
  datasource:
    driver-class-name: # driver
    jdbcUrl: # url
    username: # username
    password: # password